use_frameworks!

platform :ios, '10.0'

target 'DYDemoTest_Example' do
  pod 'DYDemoTest', :path => '../'

  target 'DYDemoTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end

end
